export { createDatabase, migrateDatabase } from "./schema/db.js";
export type { Database } from "./schema/db.js";
export { deals, documents, auditEvents, stageTransitions, entities, relationships, artifacts, spreads, covenants, covenantTests, waivers, ingestions, bankTransactions, alerts, communications, facilities, approvalRequests, } from "./schema/tables.js";
export { DealService } from "./services/deal.js";
export type { CreateDealInput, UpdateDealInput } from "./services/deal.js";
export { DocumentService } from "./services/document.js";
export type { UploadDocumentInput } from "./services/document.js";
export { AuditService } from "./services/audit.js";
export type { AuditEventInput } from "./services/audit.js";
export { StageService, STAGE_GUARDS } from "./services/stage.js";
export type { UserContext, GuardContext, StageGuard } from "./services/stage.js";
export { EntityService } from "./services/entity.js";
export type { CreateEntityInput, UpdateEntityInput } from "./services/entity.js";
export { RelationshipService } from "./services/relationship.js";
export type { CreateRelationshipInput } from "./services/relationship.js";
export { TemplateService } from "./services/template.js";
export type { Template, RenderInput, RenderOutput } from "./services/template.js";
export { ArtifactService } from "./services/artifact.js";
export type { FreezeArtifactInput } from "./services/artifact.js";
export { SpreadService, computeRatios } from "./services/spread.js";
export type { CreateSpreadInput, LineItem, Ratios, MetricsInput } from "./services/spread.js";
export { CovenantService } from "./services/covenant.js";
export type { CreateCovenantInput, CreateWaiverInput, CovenantTestResult } from "./services/covenant.js";
export { MonitoringService } from "./services/monitoring.js";
export type { IngestInput, TransactionInput, MonitoringStatus, LiquidityStatus, Alert } from "./services/monitoring.js";
export { EmailService } from "./services/email.js";
export type { EmailIngestInput, EmailIngestResult, AttachmentInfo, CommunicationRecord } from "./services/email.js";
export { FacilityService } from "./services/facility.js";
export type { CreateFacilityInput, UpdateFacilityInput } from "./services/facility.js";
export { ApprovalService } from "./services/approval.js";
export type { CreateApprovalRequestInput, DecideApprovalInput } from "./services/approval.js";
export { AppError, NotFoundError, ValidationError, StageGuardError, InvalidTransitionError, ForbiddenError, OverrideRequiredError, ConflictError, } from "./services/errors.js";
//# sourceMappingURL=index.d.ts.map