/**
 * Shadow CLI - Sync Engine Types
 *
 * Types for the synchronization engine that manages bidirectional
 * data flow between Open LOS and external systems of record.
 *
 * The sync engine operates on three principles:
 * 1. Every field carries provenance metadata (where it came from)
 * 2. Conflicts are detected, not silently resolved
 * 3. The sync plan is always previewable before execution (dry-run)
 */

import type { CanonicalEntity, AdapterType } from "../adapters/types.js";

// =============================================================================
// Provenance Tracking
// =============================================================================

/**
 * Tracks where a field value came from and when it was last synced.
 * Stored per-field, per-record in the shadow ledger.
 */
export interface FieldProvenance {
  /** Which adapter produced this value */
  source: AdapterType | "manual" | "ai" | "computed";
  /** Object type in the source system (e.g., "Opportunity", "hs_deal") */
  sourceObjectType: string;
  /** Field name in the source system (e.g., "Amount", "dealstage") */
  sourceFieldName: string;
  /** Record ID in the source system */
  sourceRecordId: string;
  /** When this value was last synced */
  lastSyncedAt: string;
  /** Direction of the last sync */
  syncDirection: "inbound" | "outbound" | "bidirectional";
  /** Confidence score (0-1) for AI-extracted or fuzzy-matched values */
  confidence?: number;
}

// =============================================================================
// Sync State per Record
// =============================================================================

/**
 * Tracks the sync state of a single record between
 * the shadow ledger and the external system.
 */
export interface SyncRecord {
  /** Internal record ID */
  id: string;
  /** Connection ID */
  connectionId: string;
  /** Canonical entity type */
  entity: CanonicalEntity;
  /** Record ID in Open LOS */
  internalId: string;
  /** Record ID in the external system */
  externalId: string;
  /** Current sync status */
  status: SyncStatus;
  /** Hash of the last synced state (for change detection) */
  lastSyncHash?: string;
  /** Last successful sync timestamp */
  lastSyncedAt?: string;
  /** Last sync error (if status is "error") */
  lastError?: string;
  /** Per-field provenance */
  fieldProvenance: Record<string, FieldProvenance>;
  /** Created timestamp */
  createdAt: string;
  /** Updated timestamp */
  updatedAt: string;
}

export type SyncStatus =
  | "synced"       // In sync with external system
  | "pending_in"   // Inbound changes waiting to be applied
  | "pending_out"  // Outbound changes waiting to be pushed
  | "conflict"     // Both sides changed — needs resolution
  | "error"        // Last sync failed
  | "new"          // Newly discovered, not yet synced
  | "orphaned";    // Exists locally but deleted externally

// =============================================================================
// Sync Plan (dry-run / preview)
// =============================================================================

/**
 * A sync plan describes what would happen if the sync is executed.
 * Generated by the sync engine before any mutations occur.
 */
export interface SyncPlan {
  /** Unique plan ID */
  planId: string;
  /** Connection ID */
  connectionId: string;
  /** When the plan was generated */
  generatedAt: string;
  /** Sync direction */
  direction: "inbound" | "outbound" | "bidirectional";
  /** Individual operations */
  operations: SyncOperation[];
  /** Conflicts that need resolution before sync can proceed */
  conflicts: SyncConflict[];
  /** Summary statistics */
  summary: SyncPlanSummary;
}

export interface SyncPlanSummary {
  creates: number;
  updates: number;
  deletes: number;
  unchanged: number;
  conflicts: number;
  errors: number;
  /** Breakdown by entity type */
  byEntity: Record<string, {
    creates: number;
    updates: number;
    deletes: number;
  }>;
}

export interface SyncOperation {
  /** Operation type */
  type: "create" | "update" | "delete";
  /** Direction of this operation */
  direction: "inbound" | "outbound";
  /** Target entity type */
  entity: CanonicalEntity;
  /** External record ID */
  externalId: string;
  /** Internal record ID (null for creates) */
  internalId?: string;
  /** Fields that will change */
  changes: FieldChange[];
}

export interface FieldChange {
  field: string;
  oldValue: unknown;
  newValue: unknown;
  /** Where the new value came from */
  source: string;
}

// =============================================================================
// Conflict Resolution
// =============================================================================

export interface SyncConflict {
  /** Conflict ID */
  id: string;
  /** Entity type */
  entity: CanonicalEntity;
  /** External record ID */
  externalId: string;
  /** Internal record ID */
  internalId: string;
  /** Field with the conflict */
  field: string;
  /** Value in the external system */
  externalValue: unknown;
  /** Value in Open LOS */
  internalValue: unknown;
  /** When the external value was modified */
  externalModifiedAt?: string;
  /** When the internal value was modified */
  internalModifiedAt?: string;
  /** Suggested resolution */
  suggestedResolution: ConflictResolution;
  /** User's chosen resolution (null until resolved) */
  resolution?: ConflictResolution;
  /** Who resolved it */
  resolvedBy?: string;
  /** When it was resolved */
  resolvedAt?: string;
}

export type ConflictResolution =
  | "keep_external"    // Source of record wins
  | "keep_internal"    // Open LOS value wins
  | "keep_newest"      // Most recently modified wins
  | "manual";          // User must decide

/**
 * Per-field conflict strategy configuration.
 * Allows different resolution strategies for different field types.
 */
export interface ConflictStrategy {
  /** Default strategy for all fields */
  default: ConflictResolution;
  /** Override strategy per entity.field */
  overrides: Record<string, ConflictResolution>;
}

// =============================================================================
// Sync Execution Result
// =============================================================================

export interface SyncResult {
  /** Sync run ID */
  runId: string;
  /** Connection ID */
  connectionId: string;
  /** Plan ID that was executed */
  planId: string;
  /** Overall status */
  status: "completed" | "partial" | "failed";
  /** When the sync started */
  startedAt: string;
  /** When the sync finished */
  completedAt: string;
  /** Results per operation */
  results: SyncOperationResult[];
  /** Summary */
  summary: {
    totalOperations: number;
    succeeded: number;
    failed: number;
    skipped: number;
  };
  /** Errors */
  errors: SyncError[];
}

export interface SyncOperationResult {
  operation: SyncOperation;
  success: boolean;
  /** Internal ID (after create or update) */
  internalId?: string;
  /** Error if failed */
  error?: string;
}

export interface SyncError {
  type: "validation" | "transform" | "api" | "conflict" | "permission";
  entity: CanonicalEntity;
  externalId?: string;
  internalId?: string;
  field?: string;
  message: string;
  details?: Record<string, unknown>;
}

// =============================================================================
// Connection Profile
// =============================================================================

/**
 * A connection profile stores everything needed to connect to
 * and sync with an external system. Saved to local config.
 */
export interface ConnectionProfile {
  /** Unique connection ID */
  id: string;
  /** Human-readable name */
  name: string;
  /** Adapter type */
  adapterType: AdapterType;
  /** Connection config (credentials stored separately) */
  config: Record<string, unknown>;
  /** Confirmed field mappings */
  mappings: import("../adapters/types.js").FieldMapping[];
  /** Conflict resolution strategy */
  conflictStrategy: ConflictStrategy;
  /** Sync schedule (cron expression, or "manual") */
  syncSchedule: string;
  /** Phase of shadow adoption */
  phase: ShadowPhase;
  /** When this connection was created */
  createdAt: string;
  /** When this connection was last modified */
  updatedAt: string;
  /** When the last sync completed */
  lastSyncAt?: string;
  /** Status of the connection */
  status: "active" | "paused" | "error" | "disconnected";
}

export type ShadowPhase =
  | "mirror"       // Phase 1: read-only inbound sync
  | "enrichment"   // Phase 2: inbound + local analytics
  | "writeback"    // Phase 3: bidirectional sync
  | "primary";     // Phase 4: Open LOS is the system of record

// =============================================================================
// Shadow Status
// =============================================================================

/**
 * Overall status of the shadow CLI — displayed by `los shadow status`.
 */
export interface ShadowStatus {
  /** Active connections */
  connections: ConnectionSummary[];
  /** Aggregate record counts */
  recordCounts: Record<CanonicalEntity, number>;
  /** Pending operations */
  pendingInbound: number;
  pendingOutbound: number;
  conflicts: number;
  /** Field mapping health */
  mappingCoverage: number;
  /** Enrichment summary (fields computed by Open LOS that don't exist in SoR) */
  enrichedFields: number;
}

export interface ConnectionSummary {
  id: string;
  name: string;
  adapterType: AdapterType;
  phase: ShadowPhase;
  status: "active" | "paused" | "error" | "disconnected";
  lastSyncAt?: string;
  recordCount: number;
  pendingChanges: number;
  conflicts: number;
}
